### ISSUE TITLE
Possible typo in "compute_euclidean_distances.py"

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [soda-inria/sklearn-numba-dpex#36]
[Lines 53-54](https://github.com/soda-inria/sklearn-numba-dpex/blob/a139514697d87c51c155afea7006bb9c2512ccad/sklearn_numba_dpex/kmeans/kernels/compute_euclidean_distances.py#L53-L54) of "compute_euclidean_distances.py" read

```python
    n_windows_per_feature = math.ceil(n_clusters / window_n_centroids)
    n_windows_per_centroid = math.ceil(n_features / centroids_window_height)
```

Perhaps it should be 

```python
    n_windows_per_centroid = math.ceil(n_clusters / window_n_centroids)
    n_windows_per_feature = math.ceil(n_features / centroids_window_height)
```

**Comment by fcharras** [comment]
Thanks for reporting @oleksandr-pavlyk 

I don't think there's a typo but the naming is confusing, here `n_windows_per_xxx` refers to the total number of windows to cover the dimension that is orthogonal to xxx. If `n_windows_accross_features` instead of `n_windows_per_centroid` and `n_windows_accross_centroids` instead of `n_windows_per_feature`  is better naming I will rename in future PRs.

**Comment by fcharras** [comment]
Ty for the suggestion, `n_windows_for_...` is much better
